inherit "/std/monster";

#include "../domain.h"

void setup(void) {
  set_name("Cyberslime");
add_id("cyberslime");
add_id("cyber");
add_id("slime");
  set_short( "Cyberslime" );
  set_long( "You see before you a huge metallic blob of some unknown substance. It is pulsating weakly, the metallic skin changing tones and contours with each pulse. Within the metallic outer layer itself is a visible inner layer of some glowing stuff. Each pulse sends a ripple all over the cyberslime's tangible form. This is not just another ooze... this must be the amalgamation of the ooze and and the radiation generated by the reactor. Just looking at it is giving you a slight headache." );

  set_gender("neuter");
  set_race("human");

  set_level(7);

  set_hit_skill("combat/unarmed");
  set_skill("combat/unarmed", 35);
  set_skill("combat/defense", 35);
}

void monster_died(void) {
   if (killer->is_completed_quest("Rats") == 1) {
     return;
   } else {
     if (killer->query_q7_tracker() == 1) {
       killer->set_q7_tracker(3);
     }
   }
}
