inherit "/std/room";

#include "../../domain.h" 
void setup( void ) {

  #include "area.h"

  set_property("x", 170);
  set_property("y", 450);
  set_property("z", -10);

  add_area( "prisonbasement" );
  set_short( "Reactor Deck" );
  set_long( "The large light plates on the ceiling is the source of this room's brightness. The light reflects off the outer hull of the reactor, and even leaves a glint on the deck's slightly vibrating floor. Big as this room is, the light generated by the plates is more than sufficient to illuminate it.\n\nTo the north is the monitoring station. Going south will take you to the main control center, or you can go west into the rod control room." );


  set_objects( 
 DIR+"/monsters/r1physicist.c", 
 DIR+"/monsters/r1physicist.c", 
 DIR+"/monsters/r1engineer.c", 
 DIR+"/monsters/r1serviceman.c"
);
 set_exits( ([
  "north" : DIR+"/rooms/prisonbasement/x170y460z-10.c",
  "south" : DIR+"/rooms/prisonbasement/x170y440z-10.c",
  "west" : DIR+"/rooms/prisonbasement/x160y450z-10.c"
  ]) );
}
